### ISSUE TITLE
Watchdog timer issue with esp32? 

### ISSUE THREAD

**Issue by thagoober** [boscacci/MTA-clock-esp32#10]
I am having a hell of a time sorting through this one, and even had ChatGPT make some sense of this for me, but once I upload the code to the esp32, it gives me this message in the Output: 

Leaving...
Hard resetting via RTS pin...

Followed by this recurring error (in 10s intervals) in the Serial Monitor (which looks like a watchdog timer issue due to a loop in the code): 

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1344
load:0x40078000,len:13808
load:0x40080400,len:3608
entry 0x400805f0 

May I ask your advice on this?

**Comment by thagoober** [comment]
Holy smokes I figured it out.. I needed to connect a 3.3v + ground connection to the VSS/VDD side of the OLED, while also connecting 5v+ground as indicated. This solves the issue with the OLED loop in the code getting timed out by the watchdog timer.

**Comment by boscacci** [comment]
Nicely done sorry for the delayed response
