### ISSUE TITLE
This is not an issue, just a question!

### ISSUE THREAD

**Issue by fixingthingsguy** [boscacci/MTA-clock-esp32#5]
Hello Robert, Great job with the application. Not much of a modern techie, but wondering what the purpose of the AWS EC2 set  up was for.  
Basically I'm wondering if the MTA feed can't be received at the ESP. There are other feeds, probably for sure not as complex, that ESP can receive, for example weather underground.
So I was looking to see if that kind of model would work. 
Thanks, again, great job.
I'll delete this in a couple of days since its not a fair "issue:".
Regards

**Comment by fixingthingsguy** [comment]
Not really an issue, so closing as promised.

**Comment by boscacci** [comment]
Hi there, thanks for asking.

Programmers better than me have succeeded at parsing the MTA protobuf feed directly on the ESP32. I am not among their ranks.

Instead, here we used MTAPI (hosted on an ec2 instance, but could be hosted anywhere I guess) to translate the MTA protobuf feed into something more RESTful which the ESP32 could query more easily.

**Comment by fixingthingsguy** [comment]
Hi Robert Thanks for rhe explanation. I had seen some  very complex approaches on the internet alluding to what you said.Anyway, I'm marching along the steps you provided . The ESP I'm familar with, and I think I can figure out the EC2 implementation, with a few attempts and re-do's.Thanks for taking the trouble to post your solution.

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 27, 2022 at 2:23 PM, Robert ***@***.***> wrote:   


Hi there, thanks for asking.

Programmers better than me have succeeded at parsing the MTA protobuf feed directly on the ESP32. I am not among their ranks.

Instead, here we used MTAPI (hosted on an ec2 instance, but could be hosted anywhere I guess) to translate the MTA protobuf feed into something more RESTful which the ESP32 could query more easily.
