### ISSUE TITLE
I did a re-make

### ISSUE THREAD

**Issue by fixingthingsguy** [boscacci/MTA-clock-esp32#8]
This is not an issue, just wanted to let you know that I did a re-make of your application. Only difference was that I got it to work on an ESP8266 (aka nodemcu). Took a little bit of time(!) . I also remade the enclosure. And I used a WifiMgr that enables AutoConnect.
But the guts are the same.
Thanks for showing the way.

Next I'm going to try and figure out a way to get data from the nyct feed using a mcu rather than the EC2 on AWS, which is costing me about $10/month. No free tier for me since I had an account already.( I was able to get the Ubuntu code to host Thornton's proxy server on a Windows emulation(WSL)but I don't like the idea of others burrowingi into my Windows computer.). 

If I knew how to email you directly, I would, but dunno how.
Regards

**Comment by fixingthingsguy** [comment]
Closing!

**Comment by boscacci** [comment]
Nice! Feel free to submit a PR for your architecture, we can have it as a branch?

**Comment by fixingthingsguy** [comment]
I will do that. I need to make it pretty provide the software mods I made.

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 16, 2023 at 12:29 PM, Robert ***@***.***> wrote:   


Nice! Feel free to submit a PR for your architecture, we can have it as a branch?
